export const INITIAL_SUCCESS = 'APP/INITIAL_SUCCESS'
export const SET_ERROR = 'APP/SET_ERROR'

export const SET_AUTH_DATA = 'AUTH/SET_AUTH_DATA'
export const SET_CAPTCHA = 'AUTH/SET_CAPTCHA'

export const ADD_MESSAGE = 'DIALOGS/ADD_MESSAGE'

export const ADD_POST = 'PROFILE/ADD-POST'
export const SET_PROFILE = 'PROFILE/SET_PROFILE'
export const SET_STATUS = 'PROFILE/SET_STATUS'
export const DELETE_POST = 'PROFILE/DELETE_POST'
export const SET_EDIT_MODE = 'PROFILE/SET_EDIT_MODE'
export const UPLOAD_PHOTO_SUCCESS = 'PROFILE/UPLOAD_PHOTO_SUCCESS'
export const IS_LOADING = 'PROFILE/IS_LOADING'

export const FOLLOW = 'USERS/FOLLOW'
export const UNFOLLOW = 'USERS/UNFOLLOW'
export const SET_USERS = 'USERS/SET_USERS'
export const SET_TOTAL_COUNT_PAGES = 'USERS/SET_TOTAL_COUNT_PAGES'
export const SET_CURRENT_PAGE = 'USERS/SET_CURRENT_PAGE'
export const SET_PORTION = 'USERS/SET_PORTION'
export const SET_IS_LOADING = 'USERS/SET_IS_LOADING'
export const TOGGLE_IS_FOLLOWING_PROGRESS = 'USERS/TOGGLE_IS_FOLLOWING_PROGRESS'